services:
  embedding-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embedding-server
    networks:
      - internal-net

networks:
  internal-net:
    external: true
