
services:
  kafka-consumer:
    image: python:3.12-slim
    container_name: embedding-server
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "pip install -r requirements.txt &&
             python KafkaConsumer.py"
    networks:
      - internal-net


networks:
  internal-net:
    external: true
    name: internal-net